### ISSUE TITLE
天賦模擬器連結更新

### ISSUE THREAD

**Issue by Hyouun** [pc035860/hi-armory.tw#3]
Hi，之前BZ有換新版英雄榜和天賦模擬器
目前hi-armory的天賦連結好像還是舊版的
舊：
https://tw.battle.net/wow/zh/tool/talent-calculator#caa!0022000
新：
https://worldofwarcraft.com/zh-tw/game/talent-calculator#rogue/assassination/talents=1133111

**Comment by pc035860** [comment]
@Hyouun 
昨天我也有發現 XD
最近正在做新的搜尋功能，上線的時候會順帶把模擬器修正。

謝謝你的回報！
